PUT http://localhost:8080/products/612bb4dbf88f3164074ed983
Content-Type: application/json

{
  "name": "Big Lattes",
  "price": 3.50
}

###

####
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Big Lattes",
  "price": 3.99
}


###
GET http://localhost:8080/products
Accept: application/json

###
GET http://localhost:8080/products/612bb402f88f3164074ed980
Accept: application/json

###
GET http://localhost:8080/products/612bb402f88f3164074ed98
Accept: application/json

